import "./globals.css";
import NavbarSwitcher from "@/Components/NavbarSwitcher";
import FoooterSwitcher from "@/Components/FoooterSwitcher";
import { ToastContainer } from "react-toastify";
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";
import whatsapp from "../../public/whatsapp.svg";
import Popup from "@/Components/Popup";

export const metadata = {
  title: "Prashna Siddhi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Google Site Verification */}
        <meta
          name="google-site-verification"
          content="PkolaIiMpfXA4n1MyV5YsHbcxnBvaODn5g53C8otKTE"
        />
      </Head>

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet"
      />
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.2.10/iframeResizer.min.js" />

      {/* ✅ Google Tag Manager - Script */}
      <Script
        id="gtm-script"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            (function(w,d,s,l,i){
              w[l]=w[l]||[];
              w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});
              var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
              j.async=true;
              j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;
              f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-PMPBF3T3');
          `,
        }}
      />

      <body className={"antialiased"}>
        {/* ✅ Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-PMPBF3T3"
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
          />
        </noscript>
        <div className="absolute right-0 bottom-0">
          <ToastContainer />
        </div>
        <NavbarSwitcher />

        {children}
        {/* ✅ WhatsApp Button */}
        <div className="fixed max-sm:hidden bottom-20 right-0 z-50 rounded-full p-2 transition-transform duration-200 md:p-5">
          <iframe
            onLoad="iFrameResize(this)"
            src="https://a99f75cab04643caa32ea3e94b386be4.elf.site"
            // style="border:none;width:100%;"
            className="h-[550px] pt-0 w-full "
          ></iframe>
        </div>

        <a
          href="https://wa.me/7259691375?text=Need%20any%20clarification,%20pls%20message."
          target="_blank"
          className="fixed bottom-4 right-4 z-50 rounded-full p-2 hover:scale-110 transition-transform duration-200 md:p-5"
        >
          <Image
            src={whatsapp}
            alt="WhatsApp"
            width={50}
            height={50}
            className="w-8 h-8 md:w-10 md:h-10"
          />
        </a>
        <FoooterSwitcher />
      </body>
    </html>
  );
}
