// import "./globals.css";

// import NavbarSwitcher from "@/Components/NavbarSwitcher";
// import FoooterSwitcher from "@/Components/FoooterSwitcher";
// import { ToastContainer } from "react-toastify";

// export const metadata = {
//   title: "Prashna Siddhi",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <meta
//         name="google-site-verification"
//         content="PkolaIiMpfXA4n1MyV5YsHbcxnBvaODn5g53C8otKTE"
//       />

//       <body className={"antialiased"}>
//         <div className="abosolute right-0 bottom-0">
//           <ToastContainer />
//         </div>
//         <NavbarSwitcher />
//         {children}
//         <FoooterSwitcher />
//       </body>
//     </html>
//   );
// }
import "./globals.css";
import NavbarSwitcher from "@/Components/NavbarSwitcher";
import FoooterSwitcher from "@/Components/FoooterSwitcher";
import { ToastContainer } from "react-toastify";
import Head from "next/head";
import Script from "next/script";
import Image from "next/image";

export const metadata = {
  title: "Prashna Siddhi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Google Site Verification */}
        <meta
          name="google-site-verification"
          content="PkolaIiMpfXA4n1MyV5YsHbcxnBvaODn5g53C8otKTE"
        />
      </Head>

      {/* Google Analytics - Load script */}
      <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=G-3L6WJBC2TL`}
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-3L6WJBC2TL');
          `,
        }}
      />

      <body className={"antialiased"}>
        <div className="absolute right-0 bottom-0">
          <ToastContainer />
        </div>
        <NavbarSwitcher />
        {children}

        <a
          href="https://wa.me/1234567890?text=Hello,%20I%20would%20like%20to%20inquire%20about%20your%20services."
          target="_blank"
          class="fixed bottom-4 right-4 z-50 bg-green-500 rounded-full p-4 shadow-lg hover:scale-110 transition-transform duration-200 md:p-5"
        >
          <Image
            src="https://cdn-icons-png.flaticon.com/512/124/124034.png"
            alt="WhatsApp"
            class="w-8 h-8 md:w-10 md:h-10"
          />
        </a>

        <FoooterSwitcher />
      </body>
    </html>
  );
}
